application: rails-angular-backend-demo
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /js
  static_dir: js

- url: /css
  static_dir: css

